version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgis/postgis
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /data/postgres
    volumes:
      - data:/data/postgres
      - ./script/installExtension.sql:/docker-entrypoint-initdb.d/0-installExtension.sql
    ports:
      - 5432:5432

volumes:
  data:
